### ISSUE TITLE
Trying Simple Implementation

### ISSUE THREAD

**Issue by dclechok** [Kiarash-Z/react-modern-calendar-datepicker#331]
For some reason, I'm attempting to do a very simple implementation of this calendar and I keep getting these issues.
I installed the project according to the directions, imported DatePicker from the package, and added the component to my project like so...
`<DatePicker value={date} onChange={setDate} />` where date/setDate are the state variables (initialized to null).

```
index.js:1 Uncaught TypeError: Cannot read properties of null (reading 'removeEventListener')
    at index.js:1:1
    at safelyCallDestroy (react-dom.development.js:22831:1)
    at commitHookEffectListUnmount (react-dom.development.js:22999:1)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (react-dom.development.js:24988:1)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (react-dom.development.js:24938:1)
    at commitPassiveUnmountEffects_begin (react-dom.development.js:24846:1)
    at commitPassiveUnmountEffects (react-dom.development.js:24831:1)
    at flushPassiveEffectsImpl (react-dom.development.js:26989:1)
    at flushPassiveEffects (react-dom.development.js:26935:1)
    at commitRootImpl (react-dom.development.js:26886:1)
(anonymous) @ index.js:1
safelyCallDestroy @ react-dom.development.js:22831
commitHookEffectListUnmount @ react-dom.development.js:22999
commitPassiveUnmountInsideDeletedTreeOnFiber @ react-dom.development.js:24988
commitPassiveUnmountEffectsInsideOfDeletedTree_begin @ react-dom.development.js:24938
commitPassiveUnmountEffects_begin @ react-dom.development.js:24846
commitPassiveUnmountEffects @ react-dom.development.js:24831
flushPassiveEffectsImpl @ react-dom.development.js:26989
flushPassiveEffects @ react-dom.development.js:26935
commitRootImpl @ react-dom.development.js:26886
commitRoot @ react-dom.development.js:26638
performSyncWorkOnRoot @ react-dom.development.js:26073
flushSyncCallbacks @ react-dom.development.js:12009
(anonymous) @ react-dom.development.js:25607
react-dom.development.js:18572 The above error occurred in the <F> component:

    at F (http://localhost:3000/static/js/bundle.js:63201:13)
    at div

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18572
update.callback @ react-dom.development.js:18605
callCallback @ react-dom.development.js:13122
commitUpdateQueue @ react-dom.development.js:13143
commitLayoutEffectOnFiber @ react-dom.development.js:23290
commitLayoutMountEffects_complete @ react-dom.development.js:24578
commitLayoutEffects_begin @ react-dom.development.js:24564
commitLayoutEffects @ react-dom.development.js:24502
commitRootImpl @ react-dom.development.js:26779
commitRoot @ react-dom.development.js:26638
performSyncWorkOnRoot @ react-dom.development.js:26073
flushSyncCallbacks @ react-dom.development.js:12009
(anonymous) @ react-dom.development.js:25607
index.js:1 Uncaught TypeError: Cannot read properties of null (reading 'removeEventListener')
    at index.js:1:1
    at safelyCallDestroy (react-dom.development.js:22831:1)
    at commitHookEffectListUnmount (react-dom.development.js:22999:1)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (react-dom.development.js:24988:1)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (react-dom.development.js:24938:1)
    at commitPassiveUnmountEffects_begin (react-dom.development.js:24846:1)
    at commitPassiveUnmountEffects (react-dom.development.js:24831:1)
    at flushPassiveEffectsImpl (react-dom.development.js:26989:1)
    at flushPassiveEffects (react-dom.development.js:26935:1)
    at commitRootImpl (react-dom.development.js:26886:1)

**Comment by Jesuloba-world** [comment]
I have the same issue

**Comment by R3XP** [comment]
Am having the exact same Problem. Any insight yet?

**Comment by ilya-adnymics** [comment]
This repo seems abandoned. There are multiple forks, the most popular one has a fix for this issue:
- npm https://www.npmjs.com/package/@hassanmojab/react-modern-calendar-datepicker
- source (diff with this repo) https://github.com/HassanMojab/react-modern-calendar-datepicker/commits/master

That fork seems abandoned as well though, but at least it has a fix for the current issue :smile:
