### ISSUE TITLE
error how to solve it

### ISSUE THREAD

**Issue by MyKKHub** [Kiarash-Z/react-modern-calendar-datepicker#364]
Uncaught runtime errors:
×
ERROR
Cannot read properties of null (reading 'removeEventListener')
TypeError: Cannot read properties of null (reading 'removeEventListener')
    at http://localhost:3000/static/js/bundle.js:2063:28
    at safelyCallDestroy (http://localhost:3000/static/js/bundle.js:94537:9)
    at commitHookEffectListUnmount (http://localhost:3000/static/js/bundle.js:94675:15)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (http://localhost:3000/static/js/bundle.js:96356:15)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (http://localhost:3000/static/js/bundle.js:96312:9)
    at commitPassiveUnmountEffects_begin (http://localhost:3000/static/js/bundle.js:96234:15)
    at commitPassiveUnmountEffects (http://localhost:3000/static/js/bundle.js:96222:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:98045:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:97998:18)
    at commitRootImpl (http://localhost:3000/static/js/bundle.js:97957:9)
ERROR
Cannot read properties of null (reading 'removeEventListener')
TypeError: Cannot read properties of null (reading 'removeEventListener')
    at http://localhost:3000/static/js/bundle.js:2063:28
    at safelyCallDestroy (http://localhost:3000/static/js/bundle.js:94537:9)
    at commitHookEffectListUnmount (http://localhost:3000/static/js/bundle.js:94675:15)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (http://localhost:3000/static/js/bundle.js:96356:15)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (http://localhost:3000/static/js/bundle.js:96312:9)
    at commitPassiveUnmountEffects_begin (http://localhost:3000/static/js/bundle.js:96234:15)
    at commitPassiveUnmountEffects (http://localhost:3000/static/js/bundle.js:96222:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:98045:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:97998:18)
    at commitRootImpl (http://localhost:3000/static/js/bundle.js:97957:9)
ERROR
Cannot read properties of null (reading 'removeEventListener')
TypeError: Cannot read properties of null (reading 'removeEventListener')
    at http://localhost:3000/static/js/bundle.js:2063:28
    at safelyCallDestroy (http://localhost:3000/static/js/bundle.js:94537:9)
    at commitHookEffectListUnmount (http://localhost:3000/static/js/bundle.js:94675:15)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (http://localhost:3000/static/js/bundle.js:96356:15)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (http://localhost:3000/static/js/bundle.js:96312:9)
    at commitPassiveUnmountEffects_begin (http://localhost:3000/static/js/bundle.js:96234:15)
    at commitPassiveUnmountEffects (http://localhost:3000/static/js/bundle.js:96222:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:98045:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:97998:18)
    at commitRootImpl (http://localhost:3000/static/js/bundle.js:97957:9)

**Comment by toneyavuz** [comment]
@MyKKHub  How did you solve it?
